
services:
  marketech-db:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # IMPORTANT: In production, we do not expose Postgres on the host.
    #ports:
    #  - "5432:5432"
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 20

  marketech-backend:
    build:
      context: ./backend
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.prod
    # IMPORTANT: no public ports here
    #ports:
    #  - "8000:8000"
    networks:
      - internal
      - proxy
    depends_on:
      marketech-db:
        condition: service_healthy
    volumes:
      - static_data:/app/staticfiles
      - media_data:/app/media

  marketech-frontend:
    build:
      context: ./frontend
    restart: unless-stopped
    # IMPORTANT: no public ports here (Only when running in local docker)
    #ports:
    #  - "80:80"
    networks:
      - proxy
    depends_on:
      - marketech-backend

volumes:
  postgres_data:
  static_data:
  media_data:

networks:
  internal:
  proxy:
    external: true
