
services:
  proxy:
    image: nginx:stable-alpine
    container_name: reverse-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - marketech_static_data:/staticfiles:ro
      - marketech_media_data:/media:ro
      # On ajoutera plus tard TLS/certs quand on sera sur le VPS
    networks:
      - proxy

networks:
  proxy:
    external: true

volumes:
  marketech_static_data:
    external: true
  marketech_media_data:
    external: true

